### ISSUE TITLE
Any update of LocNet?

### ISSUE THREAD

**Issue by WilliamWoo45** [ZJUYH/LocNet_caffe#1]
Hi @ZJUYH,

Firstly, thanks for providing such great work!
I would like to implement `LocNet `for the experiments. So I'm wondering when will you update the front-end of `LocNet` (release the full code of `LocNet`)?

Thanks and best regards,
William

**Comment by HuanYin94** [comment]
> Hi @ZJUYH,
> 
> Firstly, thanks for providing such great work!
> I would like to implement `LocNet `for the experiments. So I'm wondering when will you update the front-end of `LocNet` (release the full code of `LocNet`)?
> 
> Thanks and best regards,
> William

Thanks for your attention.
Yes, I will clean up my Matlab code of the front-end, and I hope I will release it in the next week.

**Comment by WilliamWoo45** [comment]
Hi, 

Thanks for your prompt reply.
I'm looking forward to that and I'll stay tuned. 

Best Regards,
William

**Comment by HuanYin94** [comment]
> Hi,
> 
> Thanks for your prompt reply.
> I'm looking forward to that and I'll stay tuned.
> 
> Best Regards,
> William

Hi William,

I upload the front-end code in a new repo. Please refer to the [LocNet_frontend](https://github.com/ZJUYH/LocNet_frontend).
If you have any questions, feel free to contact me.

Regards.

**Comment by WilliamWoo45** [comment]
Hi,

Thanks a lot for your speedy repo!
I'll implement and see.

Best Regards,
William

**Comment by HuanYin94** [comment]
The front-end code of LocNet is opened. Please refer to [LocNet_frontend](https://github.com/ZJUYH/LocNet_frontend).
